language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install --dev --prefer-source

script: vendor/bin/phpunit --coverage-clover=coverage.clover -c phpunit.xml.dist

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
